### ISSUE TITLE
No alerts received in Streamlabs

### ISSUE THREAD

**Issue by noisymime** [mathieudutour/streamlabs-github-sponsors-alerts#12]
First up **HUGE** thanks for putting this together! Github Sponsors is my preferred platform for support and having it alert through on streams would be amazing. 

Unfortunately I haven't had much luck getting this to work. Everything seems to be set up ok, I've verified the webhook in Github Sponsors and the GitHub Sponsors app is registered in my Streamlabs Dashboard, but nothing is coming through. Within Github Sponsors the webhooks are showing as being sent (And receiving a response of `{"message": "pong"}`) but I'm not sure how I can investigate further. 

Looking at the Recent Events in Streamlabs dashboard there are no entries there at all for Github sponsors. I've tried resending the webhook through Gitbhub, but nothing appears to be reaching Streamlabs. 

Are there any steps that I need perform on the Streamlabs side of things to allow these alerts / alert types?

**Comment by mathieudutour** [comment]
I'm not sure either. If you receive `pong` it means that it's the call to streamlabs which failed. I added some logs to know why.
Could you resend the webhook so that I can check?

**Comment by noisymime** [comment]
Thanks for checking this! I've just resent the request through now from Github, it got the same `pong` response. 

Here is the header that Github sent (Let me know if you need the full payload):
```
Request URL: https://q9gz5u5rw3.execute-api.eu-west-1.amazonaws.com:
Request method: POST
Accept: */*
content-type: application/json
User-Agent: GitHub-Hookshot/bbe1521
X-GitHub-Delivery: ad6d7d80-f401-11ea-9a27-6f46ac48d1f8
X-GitHub-Event: sponsorship
X-GitHub-Hook-ID: 244853531
X-GitHub-Hook-Installation-Target-ID: 1352
X-GitHub-Hook-Installation-Target-Type: sponsorslisting
X-Hub-Signature: sha1=992b06bb343a00f866525d334ec38516cff7b949
```

I sign into Streamlabs as a YouTube account rather than Twitch, just in case this makes any difference to the alert type or anything.

**Comment by mathieudutour** [comment]
Ah it seems streamlabs changed their API a bit. It should work now

**Comment by noisymime** [comment]
Awesome, it does indeed appear to be working now! Thank you SO much for looking at this.

(As an aside, do you know if there's any way to customise these alerts through Streamlabs at all? Currently it uses the default zombie gif, but there doesn't seem to be an alert type that can be customised for these. Not a big deal, but thought I'd ask).

**Comment by mathieudutour** [comment]
> do you know if there's any way to customise these alerts through Streamlabs at all?

It's not possible to customise them through Streamlabs but it is possible to customise them through the API.
I already have the model prepared (https://github.com/mathieudutour/streamlabs-github-sponsors-alerts/blob/master/backend/lib/model/user.ts#L15-L21, https://github.com/mathieudutour/streamlabs-github-sponsors-alerts/blob/master/backend/lib/webhook/github.ts#L161-L183) but haven't made any frontend to set them.

I don't have much time to spend on it but I'd be happy to review a PR
